---
collections:
- name: community.vmware
  source: https://galaxy.ansible.com
- name: community.general
  source: https://galaxy.ansible.com
- name: community.mysql
  source: https://galaxy.ansible.com
- name: redhat.demo_collection
  source: aap-ah01.infra.dszlab.net
#- name: middleware_automation.common_criteria
#  source: https://galaxy.ansible.com
#- name: middleware_automation.jws
#  source: https://galaxy.ansible.com
#- name: middleware_automation.redhat_csp_download
#  source: https://galaxy.ansible.com
