---
- name: "Red Hat JBoss Web Server installation and configuration"
  include_role:
    name: jws
#    - common_criteria

- name: "Ensure Tomcat is started and listen to appropriate port"
  wait_for:
    host: "{{ override_tomcat_listen_http_bind_address }}"
    port: "8080"
  when:
    - tomcat_systemd_enabled is defined
