---

- name: Include Web server deployment task
  include_tasks: task-deploy-web.yml
  when: var_deploy_web == 'enabled'

- name: Include DB server deployment task
  include_tasks: task-deploy-db.yml
  when: var_deploy_db == 'enabled'
