---
- name: Update VM on Vmware
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_name: "dummy"

  roles:
    - role: vmw
      #instance_role: "undefined"
      vmw_create_vmware_guest_task: False
      vmw_update_vmware_guest_task: True
