---
- name: Update a virtual machine state
  vmware_guest:
    validate_certs: no
    datacenter: "{{ vmw_datacenter }}"
    cluster: "{{ vmw_cluster }}"
    folder: "{{ vmw_vm_folder }}"
    name: "{{ vmw_vmname }}"
    state: "{{ vmw_state }}"
    force: "{{ vmw_force }}"
  delegate_to: localhost
  register: deployvm
  
